booksearch/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.booksearch, name='booksearch'),
    # dilanjutkan ...
]

lab08/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('booksearch.urls')),
	path('story9/', include('story9.urls')),
]

story9/urls.py
from django.urls import path, include
from .views import view_story9, view_login, view_logout

app_name="Story9"
urlpatterns = [
    path('', view_story9, name="story9"),
    path('login/', view_login, name="login"),
    path('logout/', view_logout, name="logout")
]

booksearch/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

booksearch/views.py
from django.shortcuts import render

# Create your views here.
def booksearch(request):

	
    return render(request, 'booksearch.html')

story9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required

# Create your views here.
# @login_required(login_url='/story9/login/')
def view_story9(request):
    return render(request, "home.html")

def view_login(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('/story9')
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})

def view_logout(request):
    logout(request)
    return redirect('/story9')

booksearch/templates/booksearch.html
<!doctype html>
<html lang="en">
{% load static %}



<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Find your book!</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src = "{% static 'js/story8.js' %}"></script>
    <link href="{% static 'css/search.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Heebo:500&display=swap" rel="stylesheet">


</head>

<body>
<div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-6">
        <h1 id="judul"> Find your book here!</h1>
    </div>
    <div class="col-md-3">
    </div>
</div>
<div class="row">
    <div class="col-md-4">
    </div>
    <div class="col-md-4">
        <input class="form-control" id="search" placeholder="Title or Author">
        <button id="button" class="btn btn-info" type="button"> Search </button>
        {% if user.is_authenticated %}

        <a href="{% url 'Story9:logout' %}">
            <button id="logout" class="btn btn-info">Logout</button>
        </a>
        {% else %}

        <a href="{% url 'Story9:login' %}">
            <button id="button" class="btn btn-info" type="button"> Login </button>
        </a>
        {% endif %}

    </div>
    <div class="col-md-4">
    </div>
</div>
<div class="row">
    <div class="col-md-2">
    </div>
    <div class="col-md-8">
        <div id="results">
            <table class="table"></table>
        </div>
    </div>
    <div class="col-md-2">
    </div>
</div>

</body>

story9/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <title>Please login!</title>
</head>
<body>

    {% if user.is_authenticated %}
    <h1>Hello, {{ user }}</h1>
    <a href="{% url 'Story9:logout' %}">
        <button id="logout" class="btn btn-info">Logout</button>
    </a>
    <a href="{% url 'homepage:booksearch' %}">
        <button id="logout" class="btn btn-info">Books</button>
    </a>
    {% else %}
    <h1>
        Please login!
    </h1>
    <a href="{% url 'Story9:login' %}">
            <button id="login" class="btn btn-info">Login</button>
    </a>
    <a href="{% url 'homepage:booksearch' %}">
        <button id="logout" class="btn btn-info">Books</button>
    </a>
    {% endif %}

</body>
</html>

story9/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <title>Story 9 Login</title>
</head>
<body>
    <form class="auth-form" action="{% url 'Story9:login' %}" method="POST">
        {% csrf_token %}
        <label for="id_username">Username:</label>
        <input type="text" name="username" autofocus="" required="" id="id_username">
        <label for="id_password">Password:</label>
        <input type="password" name="password" required="" id="id_password">
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}
        <input type="submit" id="login" value="Login">
    </form>
</body>
</html>